DICOM_FOLDER: 'C:\Users\yiwei\Documents\20241015\test'
FIRST_DICOM_FILENAME: '374.30.1'

SLICE_NUM: 5
IMG_PER_SCAN: 15
SLICE_SPACING: 1

INIT_TEMP: 0
MAX_TEMP: 50

# PLOT_ENABLED: False
PLOT_ENABLED: True
CEM_REF_TEMP: 43
IGTL_ENABLED: False
IGTL_LIB: 'pyigtl' # 'pyigtl' or 'openigtlink'
IGTL_PORT: 18900